### ISSUE TITLE
Jukebox test fix

### ISSUE THREAD

**Issue by dougtebay** [learn-co-curriculum/jukebox-cli#13] opened 2015-09-01 16:36 UTC
Hi, to get the test for Jukebox working it's necessary to change line 1 of spec_helper.rb from "require_relative '../jukebox'" to "require_relative '../lib/jukebox'".

**Comment by AnnJohn** [comment] 2015-09-02 14:48
Hi @dougtebay and thanks for raising the issue. Since this issue is a duplicate of  #12   I will reference your issue there and will close this. Thanks again.

**Closed by AnnJohn** 2015-09-02 14:48 UTC

**Comment by dougtebay** [comment] 2015-09-03 00:05
Hi Ann, sorry if I'm duplicating an issue that was already raised. The Learn lab links to a different repository where I didn't see any issues listed (https://github.com/learn-co-students/guessing-cli-001-prework-web). Hope I'm driving you crazy with all the feedback!

**Comment by dougtebay** [comment] 2015-09-03 00:06
*NOT driving you crazy :)
